{{- $keycloakRealm := default "exampleRealm" .Values.global.config.keycloakRealm -}}
{{- $keycloakTlsForDebug := ternary "s" "" ( and .Values.global.debugMode.enabled .Values.global.tls.enabled ) -}}
{{- $projectDomain := default "exampledomain.eu" .Values.global.projectDomain -}}
{{- $keycloakDomainForDebug := ternary ( printf ".%s" $projectDomain ) "" .Values.global.debugMode.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-secret-uploader.fullname" . }}
  labels:
    {{- include "vault-secret-uploader.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vault-secret-uploader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vault-secret-uploader.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vault-secret-uploader.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: VAULT_SECRET_UPLOADER_PORT
            value: {{ .Values.service.targetPort | quote }}
          - name: OIDC_CLIENT_ID
            value: {{ default "exampleClient" .Values.global.config.keycloakClient | quote }}
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-postinstall
                key: client-secret
          - name: OIDC_INTROSPECTION_ENDPOINT
            value: "http{{ $keycloakTlsForDebug }}://keycloak{{ $keycloakDomainForDebug }}/realms/{{ $keycloakRealm }}/protocol/openid-connect/token/introspect"
          - name: VAULT_ADDRESS
            value: "vault"
          - name: VAULT_PORT
            value: "80"
          - name: VAULT_ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault
                key: root-token
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
