apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: prometheus
  namespace: permedcoe
spec:
  ports:
  - name: prometheus
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
