apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: permedcoe
spec:
  ports:
  - name: keycloak
    port: 80 
    protocol: TCP
    targetPort: 8080
  selector:
    app: keycloak
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

