apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secret-uploader
  namespace: permedcoe-services
spec:
  selector:
    matchLabels:
      app: vault-secret-uploader
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-secret-uploader
    spec:
      containers:
      - image: sodaliteh2020/vault-secret-uploader
        name: vault-secret-uploader
        env:
        - name: VAULT_ADMIN_TOKEN
          valueFrom:
              secretKeyRef:
                name: vault
                key: root-token
        - name: VAULT_SECRET_UPLOADER_PORT
          value: "8202"
        - name: OIDC_CLIENT_ID
          valueFrom:
              secretKeyRef:
                name: keycloak
                key: client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: keycloak
                key: client-secret
        - name: OIDC_INTROSPECTION_ENDPOINT
          valueFrom:
              secretKeyRef:
                name: keycloak
                key: introspect-url
        - name: VAULT_ADDRESS
          value: vault
        - name: VAULT_PORT
          value: "80"
        ports:
        - containerPort: 8202
          protocol: TCP
 
