apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secret-uploader
  namespace: permedcoe-services
spec:
  selector:
    matchLabels:
      app: vault-secret-uploader
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-secret-uploader
    spec:
      initContainers:
      - name: init-vault
        image: curlimages/curl
        command: ['sh', '-c', 
          '
          set -xe
          curl -X POST -H "x-vault-token: ${VAULT_TOKEN}" -d "{
                \"type\": \"jwt\",
                \"description\": \"JWKS auth\",
                \"config\": {
                    \"default_lease_ttl\": 30,
                    \"max_lease_ttl\": 30
                }
            }" http://${VAULT_HOST}:${VAULT_PORT}/v1/sys/auth/jwt;
          for ENGINE in ${VAULT_ENGINES}; do 
            curl -X POST -H "x-vault-token: ${VAULT_TOKEN}" -d "{
                \"path\": \"${ENGINE}\",
                \"type\": \"kv\",
                \"config\": {},
                \"options\": {
                    \"version\": 1
                },
                \"generate_signing_key\": true
            }" http://${VAULT_HOST}:${VAULT_PORT}/v1/sys/mounts/${ENGINE};
          done;
          curl -X POST -H "x-vault-token: ${VAULT_TOKEN}" -d "{
                \"jwks_url\": \"http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs\"
            }" http://${VAULT_HOST}:${VAULT_PORT}/v1/sys/auth/jwt/config;']
        env:
        - name: KEYCLOAK_HOST
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak-host
        - name: KEYCLOAK_PORT
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak-port
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak-realm
        - name: VAULT_HOST
          valueFrom:
            secretKeyRef:
              name: vault
              key: vault-host
        - name: VAULT_PORT
          valueFrom:
            secretKeyRef:
              name: vault
              key: vault-port
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault
              key: root-token
        - name: VAULT_ENGINES
          valueFrom:
            secretKeyRef:
              name: vault
              key: secret-engines
      containers:
      - image: atosariapclab/vault-secret-uploader
        name: vault-secret-uploader
        env:
        - name: VAULT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault
              key: root-token
        - name: VAULT_SECRET_UPLOADER_PORT
          value: "8202"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-secret
        - name: OIDC_INTROSPECTION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: introspect-url
        - name: VAULT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: vault
              key: vault-host
        - name: VAULT_PORT
          valueFrom:
            secretKeyRef:
              name: vault
              key: vault-port
        ports:
        - containerPort: 8202
          protocol: TCP
 
