apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana
  namespace: permedcoe-services
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: permedcoe-services
  labels:
    app: grafana
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  storageClassName: grafana
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/mnt/k8s-volumes/grafana"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
          - apclserver

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: permedcoe-services
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: grafana
