{{- if .Values.ingress.enabled -}}
{{- $fullName := include "keycloak.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
    cert-manager.io/issuer: {{ $fullName }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{-  $projectDomain := default "exampledomain.eu" .Values.global.projectDomain -}}
  {{- if .Values.global.tls.enabled }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hostSubdomains }}
        - {{ printf "%s.%s" . $projectDomain | quote }}
        {{- end }}
      secretName: {{ $fullName }}-tls-cert
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ printf "%s.%s" .hostSubdomain $projectDomain  | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
