# Default values for vault-secret-uploader.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.

global:
  # This enables communication towards Keycloak using ingress instead
  # of service. This is required for debugging since Keycloak's JWT
  # token is obtained from outside the cluster and it is only valid for
  # the same endpoint.
  debugMode:
    enabled: false
  # The domain name assigned to the project is a parameter intended
  # to be set from the "orchestrator" umbrella chart.
  # If omitted, "exampledomain.eu" is used for testing porposes.
  projectDomain: ""
  tls:
    enabled: false
    # The email address to be associated with the ACME account
    # (make sure it's a valid one).
    # If omitted, "ari-aida-tech@lists.atos.research.eu" is used.
    acmeEmail: ""
    # The URL used to access the ACME server’s directory endpoint.
    # If omitted, "https://acme-staging-v02.api.letsencrypt.org/directory" is used.
    acmeServer: ""
  config:
    keycloakRealm: ""
    keycloakClient: ""

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
image:
  repository: "atosariapclab/vault-secret-uploader"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

readinessProbe:
  enabled: false
  initialDelaySeconds: 8
  path: / #

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1000m
  #   memory: 1Gi
  # requests:
  #   cpu: 500m
  #   memory: 512Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8202

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: content-type, Authorization, Tenant
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - hostSubdomain: vault-secret-uploader
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hostSubdomains:
        - vault-secret-uploader