apiVersion: v1
kind: Service
metadata:
  name: ruleserver
  namespace: permedcoe-services
spec:
  ports:
  - name: ruleserver
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: ruleserver
  sessionAffinity: None
  type: ClusterIP