apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: content-type, Authorization, Tenant
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: hpc-exporter
spec:
  rules:
  - host: hpc-exporter.grapevine-project.eu
    http:
      paths:
      - backend:
          serviceName: hpc-exporter
          servicePort: 9110
        path: /
  tls:
  - hosts:
    - hpc-exporter.grapevine-project.eu
    secretName: hpc-exporter.grapevine-project.eu
