apiVersion: v2
name: orchestrator
description: A Helm chart for Orchestrator components
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.0.6"

dependencies:
  - name: cloudify
    version: "0.2.6"
    repository: "file://../cloudify"
  - name: grafana
    version: "0.1.1"
    repository: "file://../grafana"
    tags:
      - monitoring
  - name: grafana-registry
    version: "0.1.1"
    repository: "file://../grafana-registry"
    tags:
      - monitoring
  - name: hpc-exporter
    version: "0.1.1"
    repository: "file://../hpc-exporter"
    tags:
      - monitoring
  - name: keycloak
    version: "0.3.4"
    repository: "file://../keycloak"
  - name: prometheus
    version: "0.1.2"
    repository: "file://../prometheus"
    tags:
      - monitoring
  - name: vault
    version: "0.2.3"
    repository: "file://../vault"
  - name: vault-secret-uploader
    version: "0.2.3"
    repository: "file://../vault-secret-uploader"
